# Description
# ===========
# This playbook create a SQL server and an instance of SQL Database.
# Note: Random number is used to set a globally unique name for SQL Server
#
---

- hosts: localhost
  tasks:
    - name: Prepare random postfix
      set_fact:
        rpfx: "{{ 1000 | random }}"
      run_once: yes

- hosts: localhost
  vars:
    resource_group: egi_demo_sql
    location: switzerlandnorth
    sqlserver_name: demo-db-{{ rpfx }}
    sqldb_name: sqldbtest
    admin_username: egarat
    admin_password: Passw0rd
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Create SQL Server
      azure_rm_sqlserver:
        name: "{{ sqlserver_name }}"
        resource_group: "{{ resource_group }}"
        version: 12.0
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
      register: sqlserver_info

    - name: Create instance of SQL Database
      azure_rm_sqldatabase:
        resource_group: "{{ resource_group }}"
        server_name: "{{ sqlserver_name }}"
        name: "{{ sqldb_name }}"

    - name: Display server information
      debug:
        msg: "{{ sqlserver_info }}"